name: Deploy Storefront

on:
  push:
    branches: [main]
    tags:
      - 'v*'
    paths:
      - 'src/**'
      - 'public/**'
      - 'package.json'
      - 'package-lock.json'
      - 'next.config.js'
      - 'tailwind.config.js'
      - 'tsconfig.json'
      - '.env.example'
      - 'store.config.js'
  workflow_dispatch:
  release:
    types: [published]

jobs:
  deploy-storefront:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          if ! npm ci; then
            echo "npm ci failed, trying npm install instead"
            rm -rf node_modules package-lock.json
            npm install
          fi
        
      - name: Run tests
        run: npm test -- --ci --coverage --watchAll=false --passWithNoTests
          
      - name: Skip Vercel deploy (secrets missing)
        if: ${{ !(secrets.VERCEL_TOKEN != '' && secrets.VERCEL_ORG_ID != '' && secrets.VERCEL_PROJECT_ID != '') }}
        run: echo "Skipping Vercel deploy: VERCEL_* secrets not configured. Deployment likely handled by Vercel GitHub App."

      - name: Deploy to Vercel
        if: ${{ secrets.VERCEL_TOKEN != '' && secrets.VERCEL_ORG_ID != '' && secrets.VERCEL_PROJECT_ID != '' }}
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
          working-directory: ./